{{ if eq .Language "cpp" -}}CC=g++{{ else -}}CC=gcc{{ end }}
FLAGS=-O2 -Wall -Wextra -Wfatal-errors -pedantic
BIN_DIR=bin
SRC_DIR=src
INCLUDE_DIR=include

all: build

build:
	@if [ ! -d $(BIN_DIR) ]; then mkdir $(BIN_DIR); fi
	@$(CC) $(FLAGS) -I$(INCLUDE_DIR) $(SRC_DIR)/*.{{.Language}} -o $(BIN_DIR)/main

clean:
	@rm -rf $(BIN_DIR)

run:
	@./$(BIN_DIR)/main

.PHONY: all build run clean
